apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-com-tls
spec:
  secretName: k8s-com
  issuerRef:
      name: letsencrypt-prod
      kind: ClusterIssuer
  commonName: kinolounge.vip
  dnsNames:
    - kinolounge.vip
    - www.kinolounge.vip
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - kinolounge.vip
        - www.kinolounge.vip